export { default as ArticlesComponent } from "./articles/ArticlesComponent.jsx";
export { default as NavBarComponent } from "./navbar/NavBarComponent.jsx";
export { default as PartnersComponent } from "./partners/PartnersComponent.jsx";
export { default as ServicesComponent } from "./Services/ServicesComponent.jsx";
export { default as ContactComponent } from "./contact/ContactComponent.jsx";
export { default as ValuesComponent } from "./values/ValuesComponent.jsx";
export { default as WelcomeComponent } from "./welcome/WelcomeComponent.jsx";
export { default as FormComponents } from "./formLogin/FormComponents.jsx";
export { default as AboutComponent } from "./about/AboutComponent.jsx";
